# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add Medbase Components Package 
      # This automatically add the library project since the components project is dependent on it
      run: dotnet add package MedbaseComponents
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --property:PublishDir=./Release
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        host: ${{ secrets.FTP_SERVER}}
        # FTP account username
        user: ${{ secrets.FTP_USERNAME}}
        # FTP account password
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./Release/
